using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SyncDbContext.Models
{
    public class UpsertModel<T>
    {
        public Dictionary<string, string> PropertyNames { get; set; }
        public List<string> KeyFields { get; set; }
        public List<string> AutoGeneratedFields { get; set; }
        public string SyncColumn { get; set; }
        public string FullTableName { get; set; }
    }
}